### ISSUE TITLE
Problematic `new_` instead of `::default_instance()`

### ISSUE THREAD

**Issue by ice1000** [tikv/protobuf-build#4]
https://github.com/nrc/kvproto-build/blob/12af6b9b11e03890590ee26bb95f52e4071fac6a/src/wrapper.rs#L370

Because `new_` returns an object while it's expecting a reference.

Related: https://github.com/nrc/kvproto-build/pull/2#discussion_r272327977

**Comment by nrc** [comment]
`default_instance` has a proper implementation now, so I think this can be fixed easily by using that rather than `new_` here.
