### ISSUE TITLE
Is it support 22.x.x protoc?

### ISSUE THREAD

**Issue by paomian** [tikv/protobuf-build#66]
I attempt to build rust project in my pc. and then i got this error
```
--- stdout
  The system `protoc` version mismatch, require >= 3.1.0, got 22.2.x, fallback to the bundled `protoc`
```
my protoc version is `libprotoc 22.2`
I find code https://github.com/tikv/protobuf-build/blob/8d1dfba02caec5b9d00b0e210a3ee9a4ee36dfb8/src/protobuf_impl.rs#L43-L60

so Is this lib support 22.x protoc?

**Comment by JmPotato** [comment]
I believe #67 has fixed this problem: https://github.com/tikv/protobuf-build/pull/67/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R56
