### ISSUE TITLE
Another design of this library

### ISSUE THREAD

**Issue by ice1000** [tikv/protobuf-build#8]
I start doubting the idea of eliminating all getters. I'm here to propose another design of this library (unrelated to this PR):

+ Generate non-trivial getters (which `unwrap_or_else` for you)
+ Generate trivial getters with `#[deprecated]`
+ Provide options to eliminate deprecated stuffs

PTAL @nrc

_Originally posted by @ice1000 in https://github.com/tikv/protobuf-build/pull/7#issuecomment-487214748_

**Comment by ice1000** [comment]
For reference you may checkout the current generated wrapper for raft:

https://docs.rs/raft/0.4.1/src/raft/prost/wrapper_eraftpb.rs.html

**Comment by nrc** [comment]
Yeah, I wonder what the end result should look like. I think we might think about what an optimal API over Prost looks like. I imagine it will have some 'wrapper' functions, but fewer than those here. We might also add some more functions to make coding with Prost/protobuf easier. This does feel like a significant amount of design work to get right, so I prefer to leave it until we have finished the first stage of the migration.

**Comment by ice1000** [comment]
Apologize for my carelessness -- prost itself generates the "non-trivial getters (which `unwrap_or_else` for you)" already.

Now we may consider the last two options.

**Comment by ice1000** [comment]
> non-trivial getters (which unwrap_or_else for you)

Correction: there isn't.

**Comment by ice1000** [comment]
Closing in favor of #9
